# Generated by Django 4.2.1 on 2023-06-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='areas',
            field=models.ManyToManyField(related_name='areas', to='portfolio.area'),
        ),
    ]
